# Generated by Django 5.1.1 on 2024-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(default='⭐⭐⭐⭐', max_length=5),
        ),
    ]
