# Generated by Django 5.1.1 on 2024-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://i.pinimg.com/564x/2d/79/f2/2d79f220b35720725ac20410a6b31ac5.jpg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
